name: r-reticulate
channels:
  - sebp
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.12.0
  - astor=0.8.1
  - blas=1.0
  - ca-certificates=2020.12.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2020.12.5
  - cpuonly=1.0
  - cvxopt=1.2.5
  - cvxpy=1.0.31
  - cvxpy-base=1.0.31
  - dataclasses=0.8
  - dill=0.3.3
  - ecos=2.0.7.post1
  - expat=2.3.0
  - fastcache=1.1.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - future=0.18.2
  - gast=0.4.0
  - getopt-win32=0.1
  - gettext=0.19.8.1
  - glpk=4.65
  - google-pasta=0.2.0
  - graphviz=2.47.0
  - grpcio=1.37.0
  - gts=0.7.6
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=68.1
  - importlib-metadata=3.10.1
  - intel-openmp=2021.2.0
  - joblib=1.0.1
  - jpeg=9d
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - krb5=1.17.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.76.0
  - libffi=3.3
  - libgd=2.3.2
  - libglib=2.68.1
  - libgpuarray=0.7.6
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mako=1.1.4
  - markdown=3.3.4
  - markupsafe=1.1.1
  - mkl=2020.4
  - mkl-service=2.3.0
  - msys2-conda-epoch=20160418
  - multiprocess=0.70.11.1
  - ninja=1.10.2
  - numexpr=2.7.3
  - numpy=1.19.5
  - olefile=0.46
  - openssl=1.1.1k
  - osqp=0.5.0
  - pandas=1.1.5
  - pango=1.42.4
  - pcre=8.44
  - pillow=8.2.0
  - pip=21.0.1
  - pixman=0.40.0
  - protobuf=3.15.8
  - pthread-stubs=0.4
  - pydotplus=2.0.2
  - pygpu=0.7.6
  - pyparsing=2.4.7
  - pyreadline=2.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.7.0
  - pytz=2021.1
  - pyyaml=5.4.1
  - scikit-learn=0.23.2
  - scikit-survival=0.14.0
  - scipy=1.5.3
  - scs=2.1.2
  - setuptools=49.6.0
  - six=1.15.0
  - sklearn-json=0.1.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=1.1.0
  - theano=1.0.5
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - torchvision=0.8.1
  - typing_extensions=3.7.4.3
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - vs2017_win-64=19.16.27038
  - vswhere=2.8.4
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wincertstore=0.2
  - wrapt=1.12.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxt=1.2.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
